### ISSUE TITLE
[BUG] '/api/codex/v1/connect/' does not update discovery DHT

### ISSUE THREAD

**Issue by benbierens** [codex-storage/nim-codex#406] opened 2023-04-23 09:22 UTC
Nodes discovery does not work when a node is connected to a bootstrap node using the /connect API call.
It does work when a bootstrap SPR is provided as CLI argument.
This means (I think) that there are two tables of peers: one maintained in Codex and another in libp2p-DHT. The connect API call does not correctly update the libp2p one, and so further discovery does not happen.

Alternatively: Remove connect method completely, allow only use of bootstrap node with SPR (But this requires NAT information to be correct.)

**Comment by dryajov** [comment] 2023-04-23 19:11
Indeed, the `connect` API is separate from the dht connection. There aren't two tables, rather than the two subsystems have different purposes. The correct way to initialize DHT discovery is by specifying an SPR record, the connect interface doesn't interact with that.

**Comment by dryajov** [comment] 2023-04-24 17:03
Btw, this is not a bug, it is working as intended.

**Comment by veaceslavdoina** [comment] 2023-06-27 08:13
Just to recap and personal understanding
1. We have 2 ways to connect with a remote peers
2. Codex supports DHT (UDP) and lib-p2p (TCP) for peer discovery
3. For DHT we should use only `--bootstrap-node` key
4. For lib-p2p we should use only `connect` API


> Btw, this is not a bug, it is working as intended.

If this is not a bug, may we close the issue?

**Comment by dryajov** [comment] 2023-06-28 20:43
> Just for recap and personal understanding
> 
> 1. We have 2 ways to connect with a remote peers
> 2. Codex supports DHT (UDP) and lib-p2p (TCP) for peer discovery
> 3. For DHT we should use only `--bootstrap-node` key
> 4. For lib-p2p we should use only `connect` API
> 
> > Btw, this is not a bug, it is working as intended.
> 
> If this is not a bug, may we close the issue?

Yes, thats correct. 

> If this is not a bug, may we close the issue?

I think we can close this, but lets wait for @benbierens to close this.

**Comment by gmega** [comment] 2024-03-14 12:03
Spoke to @benbierens, we can close it.

**Closed by gmega** 2024-03-14 12:03 UTC
Labels: bug
