### ISSUE TITLE
Integrate NAT Traversal

### ISSUE THREAD

**Issue by dryajov** [codex-storage/nim-codex#166] opened 2022-07-28 13:49 UTC
As per meeting on 28/7/2022, logic is as follows:
If CLI param IP present, it overrides everything.
Otherwise use NAT PNP, in combination with NAT traversal externally visible addresses.

**Comment by gmega** [comment] 2024-05-27 22:01
Duplicate of #753 (actually the other way around, but by now that one is more recent :slightly_smiling_face:)

**Closed by gmega** 2024-05-27 22:01 UTC
Labels: epic
