### ISSUE TITLE
[BUG] Ethereum private key is not checked

### ISSUE THREAD

**Issue by veaceslavdoina** [codex-storage/nim-codex#725] opened 2024-03-05 16:09 UTC
**Describe the bug**
Ethereum private key file is not checked at Codex run, when `--persistence` or `--validator` is enabled.

**To Reproduce**
1. [Build Codex](https://github.com/codex-storage/nim-codex/blob/master/BUILDING.md) from source
2. Run one of the following commands
    ```shell
     # App exits
     ./build/codex --persistence

     # App continues to run
     ./build/codex --persistence --eth-account=4242424242424242424242424242424242424242
     ./build/codex --persistence --eth-private-key=non-existing
     ./build/codex --persistence --eth-account=4242424242424242424242424242424242424242 --eth-private-key=non-existing
    ```

     Same is applicable for `--validator`.

**Expected behavior**
Codex should check existence of the Ethereum private key when that is required.

**Screenshots**
```shell
docker run --rm \
  -p 8545:8545 \
  codexstorage/codex-contracts-eth:latest

./build/codex \
  --log-level=trace \
  --persistence \
  --eth-provider=localhost:8545 \
  --eth-account=4242424242424242424242424242424242424242 \
  --eth-private-key=non-existing
```
<img width="1512" alt="Screenshot 2024-03-05 at 18 05 34" src="https://github.com/codex-storage/nim-codex/assets/20563034/8c893a85-6ae7-45e2-aa9b-96de96fbc33a">

**Environment:**
```
Codex version:  untagged build
Codex revision: 6ee1162
Nim Compiler Version 1.6.14 [Linux: amd64]
```

**Additional context**
1. Code that checks the key file - https://github.com/codex-storage/nim-codex/blob/master/codex/codex.nim#L96
2. Integration tests around that - https://github.com/codex-storage/nim-codex/blob/master/tests/integration/testcli.nim

**Comment by gmega** [comment] 2024-03-07 20:21
I can't reproduce this:

```bash
 ./build/codex --persistence --eth-private-key=non-existing
 ```
 For me, this crashes with:
 ```bash
 WRN 2024-03-07 17:20:34.411-03:00 `--nat` is set to loopback, your node wont properly announce over the DHT topics="codex" tid=158035
NOT 2024-03-07 17:20:34.412-03:00 Current bytes used for cache quota         topics="codex repostore" tid=158035 bytes=0
NOT 2024-03-07 17:20:34.412-03:00 Current bytes used for persist quota       topics="codex repostore" tid=158035 bytes=0
will check if isSyncing
ERR 2024-03-07 17:20:34.414-03:00 Could not check file permissions: does Ethereum private key file exist? topics="codex node" tid=158035
```
as expected.

**Comment by gmega** [comment] 2024-03-07 21:19
If you pass an invalid ethereum account, it will indeed happily chug along, until you try to do a marketplace request, that is. At that point it'll fail with:

```bash
ERR 2024-03-07 18:13:08.033-03:00 Purchasing error                           topics="marketplace purchases errored" tid=162468 error="unknown account 0x4242424242424242424242424242424242424242" requestId=0x68cc..149c
``` 
This won't crash the client, the only thing that's going to happen is that no request will work.

So, given that, I'd ask: what's the expected behavior here? Should Codex check on boot if the account is valid and exit if it's not? I'd support that, as it seems like it'll save some debugging time for whomever enters the wrong account.

**Comment by gmega** [comment] 2024-03-07 21:21
I wonder how @dryajov and @markspanbroek feel about this. Should we add a startup check and fail fast if the account is invalid?

**Comment by veaceslavdoina** [comment] 2024-03-08 10:22
As I've discovered, we have 2 different ways to sing transactions
1. On Geth side by specifying `--eth-account`
2. On Codex side by specifying `--eth-private-key`

So, my experiments are not accurate and we should pass just one of these switches
```shell
codex --log-level=trace --persistence --eth-account=4242424242424242424242424242424242424242
codex --log-level=trace --persistence --eth-private-key=non-existing
```

Also, we have a `waitForSync` when Codex is waiting for chain to be in sync. And when we run
```
codex --log-level=trace --persistence --eth-private-key=non-existing
```
It will show the error `Error connecting to address` but not exist.

One more mistake during the test was that I missed the protocol, as we usually do in curl
```diff
- --eth-provider=localhost:8545
+ --eth-provider=http://localhost:8545
```
```
codex \
  --log-level=trace \
  --persistence \
  --eth-provider=http://localhost:8545 \
  --eth-private-key=non-existing
```
And in that way it exist on start.

<hr>

With all that I would say we should pay attention to
1. If we plan to use 2 sign options, we should update their description, because it is not so clear that we should use just one of them
2. Should we fail fast and previously check if Eth accounts data is set correctly and then `waitForSync`?

**Comment by gmega** [comment] 2024-03-08 12:20
As per our discussions, I am dismembering this bug in two:

* [fix long timeouts in `waitForSync`](https://github.com/codex-storage/nim-codex/issues/726)
* [deprecate/remove the `--eth-account`](https://github.com/codex-storage/nim-codex/issues/727)

**Comment by gmega** [comment] 2024-03-08 19:29
Hey @veaceslavdoina I'm closing this in favour of the issues above, as per your suggestion,

**Closed by gmega** 2024-03-08 19:29 UTC
Labels: bug
