### ISSUE TITLE
[BUG] Node crashes during erasure coding

### ISSUE THREAD

**Issue by tbekas** [codex-storage/nim-codex#821] opened 2024-06-03 11:44 UTC
**Describe the bug**
Bug found by @emizzle.

Found an issue that crashes the node, and it could be that I'm doing something wrong, but thought I'd ask anyway.

This is on commit `4312e5c` , the last commit before the expiry changes (from timestamp to duration) were made.

**To Reproduce**
1. Upload a file (CID = `zDvZRwzkvz9boDSsTb3YLoe2PEWtwSHpa7CiSe8YRtjXQTBUZtJy`)
2. Create a request for storage via rest api:
```json
{
  "reward": "400",
  "duration": "1000",
  "proofProbability": "1",
  "collateral": "200",
  "expiry": "1716430952", // in future
  "nodes": 3,
  "tolerance": 1
}
```
3. `StorageRequested` contract event is fired, with CID = `zDvZRwzm7iW2yfwcVv9br3NZFppmvYqwTLzd2GvH9PaTaCdS9VmS`

4. Attempt to download the dataset using REST API: `/data/zDvZRwzm7iW2yfwcVv9br3NZFppmvYqwTLzd2GvH9PaTaCdS9VmS/network`

Then codex crashes with: 
```shell
ERR 2024-05-23 15:18:26.863+10:00 Unhandled exception in async proc, aborting topics="codex" tid=11685603 msg="index -1 not in 0 .. 0"
```
I've isolated the issue to this line in the erasure decoding, but I'm not entirely sure WHY it went wrong (`ecK` is greater than `pos`):
```nim
if idx >= encoded.rounded:
      trace "Retrieved parity block"
      shallowCopy(parityData[pos - encoded.ecK], if blk.isEmpty: emptyBlock else: blk.data) # <== FAILS HERE with pos=1, encoded.ecK=2, parityData[].len=1
      parityPieces.inc
```
https://github.com/codex-storage/nim-codex/blob/4312e5ca361c91b99508b4d4968e641a57e33a02/codex/erasure/erasure.nim#L222

Could someone lend a hand with this please?

**Expected behavior**
Erasure coding succeeds and client app continues to operate normally.

**Environment:**
 - Tag/Commit 4312e5c

**Comment by benbierens** [comment] 2024-06-10 13:18
Captured in dist-test: https://github.com/codex-storage/cs-codex-dist-tests/blob/74ca512f92955ac914996b3194d8ac123fb5678a/Tests/CodexTests/BasicTests/MarketplaceTests.cs#L89

**Comment by emizzle** [comment] 2024-06-11 07:37
Related error, but not exactly the same, which is possibly due to using `tolerance: 0` in the storage request params: https://github.com/codex-storage/nim-leopard/pull/11

**Comment by emizzle** [comment] 2024-06-14 01:59
Reproduction of the bug in an integration test here: https://github.com/codex-storage/nim-codex/commit/215023bddc134054e2b029ab4394db5209862998

**Comment by gmega** [comment] 2024-07-03 16:14
I'm closing this down as these no longer happen. Maybe there are new flavours of it, but they are not this bug.

**Closed by gmega** 2024-07-03 16:14 UTC
Labels: bug
